<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageType>Template</PackageType>
    <PackageId>T3mmy.VSA.Templates</PackageId>
    <Title>T3mmyVSA Templates</Title>
    <Description>Production-oriented .NET 10 Vertical Slice Architecture project template.</Description>
    <PackageTags>dotnet-new;templates;webapi;vertical-slice-architecture;t3mmyvsa</PackageTags>
    <TargetFramework>net10.0</TargetFramework>

    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../T3mmyvsa.Web/**/*"
             Exclude="../T3mmyvsa.Web/**/bin/**;../T3mmyvsa.Web/**/obj/**;../T3mmyvsa.Web/.vs/**;../T3mmyvsa.Web/.git/**;../T3mmyvsa.Web/.idea/**;../T3mmyvsa.Web/logs/**;../T3mmyvsa.Web/**/*.nupkg;../T3mmyvsa.Web/**/*.snupkg;../T3mmyvsa.Web/Data/Migrations/**">
      <PackagePath>content/T3mmy.VSA.Templates</PackagePath>
    </Content>
  </ItemGroup>

</Project>
